### ISSUE TITLE
[BUG] Can't connect via proxy

### ISSUE THREAD

**Issue by vespucchi** [FungY911/better-grass#11]
**Describe the bug**
Not sure how to connect via residential proxy. I've updated environment table and it's reflected in pm2 prettylist, but when i log in the dashboard it's reading vps ip not proxy therefore im getting 0% network score. Not sure how to fix this

**Screenshots**
![image](https://github.com/FungY911/better-grass/assets/56511717/20a5db54-87d9-4cc7-b734-faaa53662344)

![image](https://github.com/FungY911/better-grass/assets/56511717/e07cda73-835e-474b-89d2-ea99e2c59917)

![image](https://github.com/FungY911/better-grass/assets/56511717/0a182175-273f-4dfe-91a7-d80325f8c83a)

**Operating System (please complete the following information):**
 - Ubuntu 22.04

**NodeJS Version**
19.0.0

**Version (package.json)**
"version": "1.0.1"

**Comment by FungY911** [comment]
Hello,
Grass doesn't allow to use proxy ips.
