### ISSUE TITLE
[FIXED] IP ADDS

### ISSUE THREAD

**Issue by Houshasei** [FungY911/better-grass#14]
FIXED! 3/21/23

**Comment by Houshasei** [comment]
userid1,userid1,userid1,userid1 all of them are the same just to utilize the 4 ips in a single account.

**Comment by FungY911** [comment]
In last update you need only one ID (will set one id for all nodes).
It should connect all. 
I dont have machine to test it, soo hope it will work.

**Comment by Houshasei** [comment]
> In last update you need only one ID (will set one id for all ips). It should connect all. I dont have machine to test it, soo hope it will work.

Thanks, will be trying this now!

**Comment by Houshasei** [comment]
I can give you a machine tho to test it if you want too.

**Comment by FungY911** [comment]
> I can give you a machine tho to test it if you want too.

It would be great, please contact me on discord: fungyyy

**Comment by Houshasei** [comment]
> > I can give you a machine tho to test it if you want too.
> 
> It would be great, please contact me on discord: fungyyy

Sent you a friend request discord: qtkaybee
