### ISSUE TITLE
[BUG] After starting the script, I don’t see any device connected.

### ISSUE THREAD

**Issue by xiangxn** [FungY911/better-grass#2]
After starting the script, I don’t see any device connected.
logs only:
1|grass-cl | *.*.*.* [OPEN] Websocket is open

**Comment by FungY911** [comment]
Hello,
Did you enter the correct User ID?
For better help, show me logs of app with command `pm2 logs grass-cli`.

**Comment by FungY911** [comment]
There was no reply.
