### ISSUE TITLE
[BUG] use docker get 0% Network Score

### ISSUE THREAD

**Issue by stevenQiang** [FungY911/better-grass#24]
hi, i use docker `docker run -d -e USER_ID=xxxx-e ALLOW_DEBUG=False fungyx/better-grass`  ,why get 0% network score

**Comment by EgorCode** [comment]
Hi, use symbol "" for user ID. docker run -d -e USER_ID="xxxx"

**Comment by stevenQiang** [comment]
Thank you. I checked later and found that it did not take effect because I used IDC's IP address
