### ISSUE TITLE
if success?

### ISSUE THREAD

**Issue by arraylasted** [FungY911/better-grass#3]
what condition if success ?? i try but got some error

**Comment by arraylasted** [comment]
![image](https://github.com/FungY911/better-grass/assets/54189453/f0218307-0d4c-4f5b-9e8c-6cac667b06d3)

**Comment by arraylasted** [comment]
![image](https://github.com/FungY911/better-grass/assets/54189453/ed25d07f-7356-4a7a-b236-cb782f3234e3)

**Comment by haoolii** [comment]
after i start my VPS grass service, I found it successfully connect. but it always zero score. i not sure it Grass prevent mechanism?

**Comment by karlvlam** [comment]
I got the same issue. The program is connected but the score is always zero.

**Comment by HKby** [comment]
> I got the same issue. The program is connected but the score is always zero.

anyone solve the issue? me same

**Comment by FungY911** [comment]
Hello guys,
If you still getting 0% score, it may be due to your IP address is not residential.
