### ISSUE TITLE
0% network score

### ISSUE THREAD

**Issue by farizulhammi** [FungY911/better-grass#4]
![Screenshot_20240308_205751_Chrome](https://github.com/FungY911/better-grass/assets/50283048/6b75686a-21a1-4f18-9100-a50a494bb779)

**Comment by FungY911** [comment]
Hello, 0% score you get when the IP address is not residential.

**Comment by vespucchi** [comment]
> Hello, 0% score you get when the IP address is not residential.

I have residential proxies and still getting 0%, could it be due to provider?
